services:
  api:
    restart: unless-stopped
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: unless-stopped
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    restart: unless-stopped
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
